# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

baseurl: "/helikon-jekyll/"
url: "https://vshepel.github.io"
permalink: none

# general
kusama: https://kusama.com
polkadot: https://polkadot.com
github: https://github.com/kukabi
phone: "+90 532 7266254"
email: info@helikon.io
address: "Omer Avni Mah. Balcik Sok. 4/4 34427 Beyoglu Istanbul Turkey"

# auhor
author_github: https://github.com/kukabi
author_email: kutsal@helikon.io

collections_dir: collections
collections:
  products:
    output: true
    order:
      - subvt/index.md
      - 1kv/index.md
      - chainviz/index.md